version: '3.9'

services:
    app:
        build: .
        container_name: ${DOCKER_CONTAINER_PREFIX}-app
        volumes:
            - ./:/app
        working_dir: /app
    composer:
        image: composer
        container_name: ${DOCKER_CONTAINER_PREFIX}-composer
        volumes:
            - ./:/app
        working_dir: /app
